### ISSUE TITLE
Trouble installing the durin

### ISSUE THREAD

**Issue by adarshkumar0312** [DiamondLightSource/durin#31]
Hi team
I am trying to install the durin plugin and received the following error. Please help!
`mkdir -p ./build
h5cc -Wall -g -O2 -fpic -I./src -I./bslz4/src -std=c89 -c src/plugin.c -o build/plugin.o
In file included from /home/adkumar/hdf5_dir/build/hdf5/include/hdf5.h:21,
                 from src/plugin.c:7:
/home/adkumar/hdf5_dir/build/hdf5/include/H5public.h:340:1: error: C++ style comments are not allowed in ISO C90
  340 | //! 
      | ^
/home/adkumar/hdf5_dir/build/hdf5/include/H5public.h:340:1: note: (this will be reported only once per input file)
In file included from /home/adkumar/hdf5_dir/build/hdf5/include/H5Apublic.h:20,
                 from /home/adkumar/hdf5_dir/build/hdf5/include/hdf5.h:22,
                 from src/plugin.c:7:
/home/adkumar/hdf5_dir/build/hdf5/include/H5Ipublic.h:33:1: error: C++ style comments are not allowed in ISO C90
   33 | //! 
      | ^
/home/adkumar/hdf5_dir/build/hdf5/include/H5Ipublic.h:33:1: note: (this will be reported only once per input file)
In file included from /home/adkumar/hdf5_dir/build/hdf5/include/H5Apublic.h:21,
                 from /home/adkumar/hdf5_dir/build/hdf5/include/hdf5.h:22,
                 from src/plugin.c:7:
/home/adkumar/hdf5_dir/build/hdf5/include/H5Opublic.h:86:1: error: C++ style comments are not allowed in ISO C90
   86 | //! 
      | ^
/home/adkumar/hdf5_dir/build/hdf5/include/H5Opublic.h:86:1: note: (this will be reported only once per input file)
In file included from /home/adkumar/hdf5_dir/build/hdf5/include/H5Apublic.h:22,
                 from /home/adkumar/hdf5_dir/build/hdf5/include/hdf5.h:22,
                 from src/plugin.c:7:
/home/adkumar/hdf5_dir/build/hdf5/include/H5Tpublic.h:29:1: error: C++ style comments are not allowed in ISO C90
   29 | //! 
      | ^
/home/adkumar/hdf5_dir/build/hdf5/include/H5Tpublic.h:29:1: note: (this will be reported only once per input file)
In file included from /home/adkumar/hdf5_dir/build/hdf5/include/hdf5.h:22,
                 from src/plugin.c:7:
/home/adkumar/hdf5_dir/build/hdf5/include/H5Apublic.h:24:1: error: C++ style comments are not allowed in ISO C90
   24 | //! 
      | ^
/home/adkumar/hdf5_dir/build/hdf5/include/H5Apublic.h:24:1: note: (this will be reported only once per input file)
In file included from /home/adkumar/hdf5_dir/build/hdf5/include/hdf5.h:23,
                 from src/plugin.c:7:
/home/adkumar/hdf5_dir/build/hdf5/include/H5ACpublic.h:461:1: error: C++ style comments are not allowed in ISO C90
  461 | //! 
      | ^
/home/adkumar/hdf5_dir/build/hdf5/include/H5ACpublic.h:461:1: note: (this will be reported only once per input file)
In file included from /home/adkumar/hdf5_dir/build/hdf5/include/hdf5.h:24,
                 from src/plugin.c:7:
/home/adkumar/hdf5_dir/build/hdf5/include/H5Dpublic.h:40:1: error: C++ style comments are not allowed in ISO C90
   40 | //! 
      | ^
/home/adkumar/hdf5_dir/build/hdf5/include/H5Dpublic.h:40:1: note: (this will be reported only once per input file)
In file included from /home/adkumar/hdf5_dir/build/hdf5/include/hdf5.h:25,
                 from src/plugin.c:7:
/home/adkumar/hdf5_dir/build/hdf5/include/H5Epublic.h:170:1: error: C++ style comments are not allowed in ISO C90
  170 | //! 
      | ^
/home/adkumar/hdf5_dir/build/hdf5/include/H5Epublic.h:170:1: note: (this will be reported only once per input file)
In file included from /home/adkumar/hdf5_dir/build/hdf5/include/hdf5.h:26,
                 from src/plugin.c:7:
/home/adkumar/hdf5_dir/build/hdf5/include/H5ESpublic.h:76:1: error: C++ style comments are not allowed in ISO C90
   76 | //! 
      | ^
/home/adkumar/hdf5_dir/build/hdf5/include/H5ESpublic.h:76:1: note: (this will be reported only once per input file)
In file included from /home/adkumar/hdf5_dir/build/hdf5/include/hdf5.h:27,
                 from src/plugin.c:7:
/home/adkumar/hdf5_dir/build/hdf5/include/H5Fpublic.h:124:1: error: C++ style comments are not allowed in ISO C90
  124 | //! 
      | ^
/home/adkumar/hdf5_dir/build/hdf5/include/H5Fpublic.h:124:1: note: (this will be reported only once per input file)
In file included from /home/adkumar/hdf5_dir/build/hdf5/include/hdf5.h:28,
                 from src/plugin.c:7:
/home/adkumar/hdf5_dir/build/hdf5/include/H5FDpublic.h:266:1: error: C++ style comments are not allowed in ISO C90
  266 | //! 
      | ^
/home/adkumar/hdf5_dir/build/hdf5/include/H5FDpublic.h:266:1: note: (this will be reported only once per input file)
In file included from /home/adkumar/hdf5_dir/build/hdf5/include/H5Gpublic.h:26,
                 from /home/adkumar/hdf5_dir/build/hdf5/include/hdf5.h:29,
                 from src/plugin.c:7:
/home/adkumar/hdf5_dir/build/hdf5/include/H5Lpublic.h:86:1: error: C++ style comments are not allowed in ISO C90
   86 | //! 
      | ^
/home/adkumar/hdf5_dir/build/hdf5/include/H5Lpublic.h:86:1: note: (this will be reported only once per input file)
In file included from /home/adkumar/hdf5_dir/build/hdf5/include/hdf5.h:29,
                 from src/plugin.c:7:
/home/adkumar/hdf5_dir/build/hdf5/include/H5Gpublic.h:37:1: error: C++ style comments are not allowed in ISO C90
   37 | //! 
      | ^
/home/adkumar/hdf5_dir/build/hdf5/include/H5Gpublic.h:37:1: note: (this will be reported only once per input file)
In file included from /home/adkumar/hdf5_dir/build/hdf5/include/H5Mpublic.h:24,
                 from /home/adkumar/hdf5_dir/build/hdf5/include/hdf5.h:32,
                 from src/plugin.c:7:
/home/adkumar/hdf5_dir/build/hdf5/include/H5VLpublic.h:143:1: error: C++ style comments are not allowed in ISO C90
  143 | //! 
      | ^
/home/adkumar/hdf5_dir/build/hdf5/include/H5VLpublic.h:143:1: note: (this will be reported only once per input file)
In file included from /home/adkumar/hdf5_dir/build/hdf5/include/H5VLconnector.h:29,
                 from /home/adkumar/hdf5_dir/build/hdf5/include/H5Mpublic.h:27,
                 from /home/adkumar/hdf5_dir/build/hdf5/include/hdf5.h:32,
                 from src/plugin.c:7:
/home/adkumar/hdf5_dir/build/hdf5/include/H5Rpublic.h:44:1: error: C++ style comments are not allowed in ISO C90
   44 | //! 
      | ^
/home/adkumar/hdf5_dir/build/hdf5/include/H5Rpublic.h:44:1: note: (this will be reported only once per input file)
In file included from /home/adkumar/hdf5_dir/build/hdf5/include/H5Mpublic.h:27,
                 from /home/adkumar/hdf5_dir/build/hdf5/include/hdf5.h:32,
                 from src/plugin.c:7:
/home/adkumar/hdf5_dir/build/hdf5/include/H5VLconnector.h:1010:1: error: C++ style comments are not allowed in ISO C90
 1010 | //! 
      | ^
/home/adkumar/hdf5_dir/build/hdf5/include/H5VLconnector.h:1010:1: note: (this will be reported only once per input file)
In file included from /home/adkumar/hdf5_dir/build/hdf5/include/hdf5.h:32,
                 from src/plugin.c:7:
/home/adkumar/hdf5_dir/build/hdf5/include/H5Mpublic.h:68:1: error: C++ style comments are not allowed in ISO C90
   68 | //! 
      | ^
/home/adkumar/hdf5_dir/build/hdf5/include/H5Mpublic.h:68:1: note: (this will be reported only once per input file)
In file included from /home/adkumar/hdf5_dir/build/hdf5/include/hdf5.h:33,
                 from src/plugin.c:7:
/home/adkumar/hdf5_dir/build/hdf5/include/H5MMpublic.h:28:1: error: C++ style comments are not allowed in ISO C90
   28 | //! 
      | ^
/home/adkumar/hdf5_dir/build/hdf5/include/H5MMpublic.h:28:1: note: (this will be reported only once per input file)
In file included from /home/adkumar/hdf5_dir/build/hdf5/include/H5Ppublic.h:31,
                 from /home/adkumar/hdf5_dir/build/hdf5/include/hdf5.h:35,
                 from src/plugin.c:7:
/home/adkumar/hdf5_dir/build/hdf5/include/H5Zpublic.h:259:1: error: C++ style comments are not allowed in ISO C90
  259 | //! 
      | ^
/home/adkumar/hdf5_dir/build/hdf5/include/H5Zpublic.h:259:1: note: (this will be reported only once per input file)
In file included from /home/adkumar/hdf5_dir/build/hdf5/include/hdf5.h:35,
                 from src/plugin.c:7:
/home/adkumar/hdf5_dir/build/hdf5/include/H5Ppublic.h:239:1: error: C++ style comments are not allowed in ISO C90
  239 | //! 
      | ^
/home/adkumar/hdf5_dir/build/hdf5/include/H5Ppublic.h:239:1: note: (this will be reported only once per input file)
In file included from /home/adkumar/hdf5_dir/build/hdf5/include/hdf5.h:36,
                 from src/plugin.c:7:
/home/adkumar/hdf5_dir/build/hdf5/include/H5PLpublic.h:30:1: error: C++ style comments are not allowed in ISO C90
   30 | //! 
      | ^
/home/adkumar/hdf5_dir/build/hdf5/include/H5PLpublic.h:30:1: note: (this will be reported only once per input file)
In file included from /home/adkumar/hdf5_dir/build/hdf5/include/hdf5.h:46,
                 from src/plugin.c:7:
/home/adkumar/hdf5_dir/build/hdf5/include/H5Idevelop.h:35:1: error: C++ style comments are not allowed in ISO C90
   35 | //! 
      | ^
/home/adkumar/hdf5_dir/build/hdf5/include/H5Idevelop.h:35:1: note: (this will be reported only once per input file)
In file included from /home/adkumar/hdf5_dir/build/hdf5/include/hdf5.h:47,
                 from src/plugin.c:7:
/home/adkumar/hdf5_dir/build/hdf5/include/H5Ldevelop.h:92:1: error: C++ style comments are not allowed in ISO C90
   92 | //! 
      | ^
/home/adkumar/hdf5_dir/build/hdf5/include/H5Ldevelop.h:92:1: note: (this will be reported only once per input file)
In file included from /home/adkumar/hdf5_dir/build/hdf5/include/hdf5.h:48,
                 from src/plugin.c:7:
/home/adkumar/hdf5_dir/build/hdf5/include/H5Tdevelop.h:53:1: error: C++ style comments are not allowed in ISO C90
   53 | //! 
      | ^
/home/adkumar/hdf5_dir/build/hdf5/include/H5Tdevelop.h:53:1: note: (this will be reported only once per input file)
In file included from /home/adkumar/hdf5_dir/build/hdf5/include/hdf5.h:50,
                 from src/plugin.c:7:
/home/adkumar/hdf5_dir/build/hdf5/include/H5Zdevelop.h:77:1: error: C++ style comments are not allowed in ISO C90
   77 | //! 
      | ^
/home/adkumar/hdf5_dir/build/hdf5/include/H5Zdevelop.h:77:1: note: (this will be reported only once per input file)
In file included from /home/adkumar/hdf5_dir/build/hdf5/include/hdf5.h:69,
                 from src/plugin.c:7:
/home/adkumar/hdf5_dir/build/hdf5/include/H5FDsplitter.h:38:1: error: C++ style comments are not allowed in ISO C90
   38 | //! 
      | ^
/home/adkumar/hdf5_dir/build/hdf5/include/H5FDsplitter.h:38:1: note: (this will be reported only once per input file)
make: *** [Makefile:31: build/plugin.o] Error 1`

**Comment by c-mita** [comment]
Don't pass `-std=c89` to your compile flags - that doesn't support `//` as a comment marker.

The provided Makefile uses `-std=c99` - why notjust use that?

**Comment by adarshkumar0312** [comment]
Thank you, @c-mita it worked. I had downloaded the files from https://github.com/DiamondLightSource/durin/releases/tag/2019v1. it had -std=c89.
