### ISSUE TITLE
Improve README

### ISSUE THREAD

**Issue by xen-0** [DiamondLightSource/durin#8]
The readme was somewhat rushed and, given the strict requirements when building the HDF5 library, may not be clear enough.

**Comment by xen-0** [comment]
Part of the problem is the requirement that the HDF5 library code is relocatable - this is needed since we statically link it as part of the plugin.
Static linking is far more convenient when distributing a binary, but if a user is compiling for themselves, may not be warranted.

**Comment by xen-0** [comment]
Updated readme at: https://github.com/DiamondLightSource/durin/tree/readme_update

Anything missing @graeme-winter ? If not I'll merge that into master.

**Comment by graeme-winter** [comment]
Looked good to me so I merged it - useful to get it updated tonight
